// 승인된 발굴 후보 '법무부 월별 체류자격별 체류외국인'(data.go.kr 15100016)을 표면화.
// data/raw/approved_fileData_15100016_*.csv(년,월,체류자격,체류외국인수)에서
// 월별 총 체류외국인 추이를 파생해 lib/data/generated/monthlyResidents.ts 로 emit.
// (수집은 되나 미연동이던 소스 → 홈 월별 추이 차트로 노출)
import { readdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";

const RAW = "data/raw";
const OUT = "lib/data/generated/monthlyResidents.ts";
const DATASET = "15100016";

const empty = {
  hasData: false,
  source: "법무부 월별 체류자격별 체류외국인(data.go.kr 15100016)",
  months: [],
  latestMonth: null,
  latestTotal: null,
  firstMonth: null,
  yoyPct: null
};

async function build() {
  let files = [];
  try {
    files = (await readdir(RAW)).filter((f) => f.startsWith(`approved_fileData_${DATASET}_`) && f.endsWith(".csv"));
  } catch {
    return empty;
  }
  const latest = files.sort().at(-1);
  if (!latest) return empty;

  const buf = await readFile(join(RAW, latest));
  let text = new TextDecoder("utf-8").decode(buf);
  if ((text.match(/�/g)?.length ?? 0) > 5) text = new TextDecoder("euc-kr").decode(buf);
  const lines = text.replace(/^﻿/, "").replace(/\r/g, "").split("\n").filter((l) => l.trim());

  const byMonth = new Map();
  for (const l of lines.slice(1)) {
    const c = l.split(",");
    const y = (c[0] ?? "").trim();
    const m = (c[1] ?? "").trim();
    if (!/^\d{4}$/.test(y) || !m) continue;
    const key = `${y}-${m.padStart(2, "0")}`;
    const cnt = Number(String(c[3] ?? "").replace(/,/g, "")) || 0;
    byMonth.set(key, (byMonth.get(key) ?? 0) + cnt);
  }
  const months = [...byMonth.entries()]
    .map(([month, total]) => ({ month, total }))
    .sort((a, b) => (a.month < b.month ? -1 : 1));
  if (months.length < 6) return empty;

  const latestPoint = months.at(-1);
  let yoyPct = null;
  const [ly, lm] = latestPoint.month.split("-");
  const prev = months.find((p) => p.month === `${Number(ly) - 1}-${lm}`);
  if (prev && prev.total > 0) yoyPct = Math.round(((latestPoint.total - prev.total) / prev.total) * 1000) / 10;

  return {
    hasData: true,
    source: "법무부 월별 체류자격별 체류외국인(data.go.kr 15100016)",
    months,
    latestMonth: latestPoint.month,
    latestTotal: latestPoint.total,
    firstMonth: months[0].month,
    yoyPct
  };
}

const data = await build();
const ts =
  `// AUTO-GENERATED by scripts/build_monthly_residents.mjs — 편집 금지.\n` +
  `// 법무부 월별 체류자격별 체류외국인(승인 후보 15100016)에서 월별 총 체류외국인 추이 파생.\n` +
  `export type MonthlyResidentPoint = { month: string; total: number };\n` +
  `export type MonthlyResidents = {\n` +
  `  hasData: boolean; source: string; months: MonthlyResidentPoint[];\n` +
  `  latestMonth: string | null; latestTotal: number | null; firstMonth: string | null; yoyPct: number | null;\n` +
  `};\n` +
  `export const realMonthlyResidents: MonthlyResidents = ${JSON.stringify(data, null, 2)};\n`;

await writeFile(OUT, ts);
console.log(`monthlyResidents: ${data.months.length}개월(${data.firstMonth ?? "-"}~${data.latestMonth ?? "-"}) → ${OUT}`);
