// 미연동 소스 '범용 미리보기/차트'용 데이터 생성기.
// data/raw 의 각 소스 최신 CSV를 파싱해 {columns, rows(상한), numericCols, rowCount} 로
// lib/data/generated/genericData.ts 에 emit 한다. 홈 '추가 데이터' 섹션이 관리자가 토글한
// 소스를 이 데이터로 자동 차트/표 렌더한다. (변환 로직 없이 어떤 소스든 노출 가능)
import { readdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";

const RAW_DIR = "data/raw";
const OUT = "lib/data/generated/genericData.ts";
const MAX_ROWS = 40; // 미리보기 상한(번들 크기 보호)
const MAX_COLS = 14;

function parseCsvLine(line) {
  const result = [];
  let current = "";
  let quoted = false;
  for (let i = 0; i < line.length; i += 1) {
    const char = line[i];
    const next = line[i + 1];
    if (char === '"' && quoted && next === '"') { current += '"'; i += 1; }
    else if (char === '"') quoted = !quoted;
    else if (char === "," && !quoted) { result.push(current); current = ""; }
    else current += char;
  }
  result.push(current);
  return result;
}

function parseCsvRows(text) {
  const clean = text.replace(/^﻿/, "").replace(/\r\n/g, "\n").replace(/\r/g, "\n");
  return clean.split("\n").filter((l) => l.trim().length > 0).map(parseCsvLine);
}

function decodeCsv(buffer) {
  const decoders = ["utf-8", "euc-kr", "windows-949"];
  const scored = decoders.map((encoding) => {
    let text = "";
    try { text = new TextDecoder(encoding).decode(buffer); }
    catch { return { text: "", score: -1 }; }
    const replacementPenalty = (text.match(/�/g) ?? []).length * -20;
    const koreanScore = (text.match(/[가-힣]/g) ?? []).length;
    const commaScore = (text.match(/,/g) ?? []).length;
    return { text, score: replacementPenalty + koreanScore + commaScore };
  });
  return scored.sort((a, b) => b.score - a.score)[0].text;
}

const isNum = (v) => {
  const s = String(v ?? "").replace(/,/g, "").trim();
  return s !== "" && Number.isFinite(Number(s));
};

const files = (await readdir(RAW_DIR)).filter((f) => f.endsWith(".csv"));
const byId = new Map();
for (const f of files) {
  const m = f.match(/^(.*?)_(\d{4}-\d{2}-\d{2})\.csv$/);
  if (!m) continue;
  const [, id, date] = m;
  const cur = byId.get(id);
  if (!cur || date > cur.date) byId.set(id, { file: f, date });
}

const out = {};
for (const [id, { file }] of [...byId.entries()].sort()) {
  try {
    const rowsAll = parseCsvRows(decodeCsv(await readFile(join(RAW_DIR, file)))).filter(
      (r) => r.some((c) => String(c).trim())
    );
    if (rowsAll.length < 2) continue;
    const header = rowsAll[0].slice(0, MAX_COLS).map((h) => String(h).trim() || "—");
    const body = rowsAll.slice(1);
    const sample = body.slice(0, 30);
    const numericCols = header
      .map((_, i) => (sample.filter((r) => isNum(r[i])).length >= Math.max(1, sample.length * 0.7) ? i : -1))
      .filter((i) => i >= 0);
    const rows = body.slice(0, MAX_ROWS).map((r) => header.map((_, i) => String(r[i] ?? "").trim()));
    out[id] = { columns: header, rows, numericCols, rowCount: body.length };
  } catch (e) {
    console.warn(`skip ${id}: ${e.message}`);
  }
}

const ts =
  `// AUTO-GENERATED by scripts/build_generic_data.mjs — 편집 금지.\n` +
  `// 미연동 소스 범용 미리보기/차트용. 홈 '추가 데이터' 섹션이 토글된 소스를 이 데이터로 렌더.\n` +
  `export type GenericSource = { columns: string[]; rows: string[][]; numericCols: number[]; rowCount: number };\n` +
  `export const genericSources: Record<string, GenericSource> = ${JSON.stringify(out)};\n`;

await writeFile(OUT, ts);
console.log(`generic sources emitted: ${Object.keys(out).length} → ${OUT}`);
